K_BEST_FEATURES = 7
TSNE_2D = 2
TSNE_3D = 3
TEST_PERC = 0.3
VALIDATION_PERC = 0.1
SCALABLE = ['rate_of_interest', 'Interest_rate_spread','Upfront_charges','property_value','LTV','dtir1']
TARGET = "Status"
HIGH_CORRELATION = ['rate_of_interest', 'Interest_rate_spread', 'Upfront_charges']
MONGODB_HOST = "mongodb://localhost:27017/"
RAW_DATASET_PATH = "Loan_Default.csv"
VERBOSE_PLOT_ENABLED = True
TIMEOUT = 3000